version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: Japan
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: "08:00"
      timezone: Japan
    open-pull-requests-limit: 10
    assignees:
      - kakikubo
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "GH Actions"
      - "dependencies"
